### ISSUE TITLE
Allow POST to /delay

### ISSUE THREAD

**Issue by tmenier** [kennethreitz/httpbin#224]
The /delay endpoint currently returns a 405 (method not allowed) on POST. Any chance you could open it up to allow it? Thanks.

**Comment by sigmavirus24** [comment]
Can you enlighten us as to why this is necessary?

**Comment by johnsheehan** [comment]
We've done this for our version running at yourapihere.com. I'm personally
a fan of opening up any of the non-method endpoints to allow any method. I
just haven't gotten around to it yet.

The use case is that many POST requests take awhile to process data and
this would be able to simulate that.

+1 for the request if you want to do a pull req

**Comment by sigmavirus24** [comment]
@johnsheehan sure, I guess I'm just trying to understand what is trying to be tested. Every HTTP library I've used across a couple different languages doesn't care if there's a delay in using a specific method. So, since HTTPBin is usually used to test things, I'm trying to understand the behaviour being tested.

**Comment by tmenier** [comment]
Thanks guys. @sigmavirus24 I agree that the method shouldn't matter in a delay/timeout situation, I'm just trying to prove it to settle a [bug report](https://github.com/tmenier/Flurl/issues/32).

Thanks for this service, it's been extremely valuable in testing my project. Glad to contribute a pr, thought I'd need to learn me a little python but it looks pretty clear.

**Comment by sigmavirus24** [comment]
@tmenier yeah it makes sense to me. FWIW, if you're going to send the PR you'll be changing [this line](https://github.com/Runscope/httpbin/blob/master/httpbin/core.py#L442) to look a bit more like [this other line](https://github.com/Runscope/httpbin/blob/master/httpbin/core.py#L288). You will need to specifically mention `'GET'` in your paramter to `methods` though, otherwise you'll break the existing API.

Cheers,

**Comment by tmenier** [comment]
Thanks for the tip. For completeness there's probably several other endpoints where this change might make sense for the same reasons, but I only did /delay for this PR.
