### ISSUE TITLE
http2bin dead?

### ISSUE THREAD

**Issue by jeroen** [kennethreitz/httpbin#309]
The `HTTP/2` flavour seems down.

**Comment by sigmavirus24** [comment]
@lukasa ping

**Comment by Lukasa** [comment]
Sorry folks. The server that was running http2bin managed to just vanish off the web: literally unreachable from any IP over IPv4 or IPv6. I've since redeployed on Rackspace Carina and shot that server in the head, so http2bin.org should be back up and running again.

Sorry for the long latency there, but I've been quite unwell for the past four days so this is the first time I've had sufficient focus to migrate the service over.

**Comment by sigmavirus24** [comment]
No worries @Lukasa. Is there anyway we can help with maintaining h2bin?

**Comment by Lukasa** [comment]
So Carina should cover most of this, though if RAX wants to I'd be happy to take some credit so that I can run liveness tests against it. I used to use Runscope for that but the free plan is gone. 😟

**Comment by johnsheehan** [comment]
What did you use us for here?

**Comment by Lukasa** [comment]
Simple liveness testing: 15 minute checks to see if the service was still up.

**Comment by wong2** [comment]
http://http2bin.org/ is down again?

**Comment by Lukasa** [comment]
Yup, it is no longer being maintained. Try http://nghttp2.org/httpbin

**Comment by wong2** [comment]
thanks!
