### ISSUE TITLE
DELETE method is not supposed to support POST form

### ISSUE THREAD

**Issue by puiterwijk** [kennethreitz/httpbin#317]
According to the Flask documentation (http://flask.pocoo.org/docs/0.12/api/#flask.Request.form), request.form is only supposed to contain the urlencode parsed form with PUT and POST requests.

This means that the test_delete_endpoint_returns_body test is NOT corresponding to the Flask documentation, and the fact that it DOES work should be considered a bug in Flask.

**Comment by AdamWill** [comment]
For the record, we encountered this when running the httpbin test suite against an older version of Flask (in [EPEL](https://fedoraproject.org/wiki/EPEL) 7). The older version of Flask actually does behave as documented.

**Comment by puiterwijk** [comment]
This works since Werkzeug 0.9, although it's undocumented in Flask: https://github.com/pallets/werkzeug/blob/master/werkzeug/wrappers.py#L328

**Comment by puiterwijk** [comment]
https://github.com/pallets/flask/issues/2132 is the upstream bug about this documentation inconsistency: werkzeug <0.9 only parsed the form for POST, PUT and PATCH requests.

**Comment by sigmavirus24** [comment]
Oh, so y'all are trying to package something modern against the ancient versions that Red Hat supports in its various distributions? Yeah. We're not removing *existing behaviour* to support old versions of Flask and Werkzeug. Sorry.

**Comment by AdamWill** [comment]
Well, sure, but the point is that httpbin's expectations of Flask didn't line up with its documented behaviour. That's an inconsistency no matter how we happened to encounter it. It seems that the behaviour on Flask's part is intentional, and their response was to change the documentation, as covered in https://github.com/pallets/flask/issues/2132 , but that wasn't obvious.
