### ISSUE TITLE
Add NTLM support

### ISSUE THREAD

**Issue by ukd1** [kennethreitz/httpbin#327]
We'd like to test NTLM auth. Would you accept a PR for this?

**Comment by johnsheehan** [comment]
Yes



On January 27, 2017 at 1:00:53 PM, Russell Smith (notifications@github.com)
wrote:

We'd like to test NTLM auth. Would you accept a PR for this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Runscope/httpbin/issues/327>, or mute the thread

**Comment by sigmavirus24** [comment]
@johnsheehan I do hope you'll find someone to review the addition of a broken, insecure, and outdated authentication system. I'm not qualified to do it and there are very few who are.
