### ISSUE TITLE
GET: Header "connection: keep-alive" becames "connection: close" in respose

### ISSUE THREAD

**Issue by Luckjanov** [kennethreitz/httpbin#377]
Hello,

When I make request to GET http://httpbin.org/get with header "connection: keep-alive":
```
GET /get HTTP/1.1
Connection: keep-alive
Host: httpbin.org
User-Agent: Paw/3.1.3 (Macintosh; OS X/10.12.6) GCDHTTPRequest
```

in response body the header becames "connection: close":
```
{
  "args": {}, 
  "headers": {
    "Connection": "close", 
    "Host": "httpbin.org", 
    "User-Agent": "Paw/3.1.3 (Macintosh; OS X/10.12.6) GCDHTTPRequest"
  }, 
  "origin": "46.0.48.165", 
  "url": "http://httpbin.org/get"
}
```

**Comment by tmenier** [comment]
I'm seeing this too, thought I was losing my mind. It appears to be an issue with `/headers`, and most likely other endpoints as well.

**Comment by sigmavirus24** [comment]
This is entirely due to the fact that HTTPbin is deployed on Heroku. Between the application and the user, there is a router (and proxy) and that router has (according to the RFCs) full permission to modify certain headers including this one. Without finding some other sponsor to host HTTPbin on and doing the operational work of moving there and keeping it running, there's little to be done in this case.

**Comment by tmenier** [comment]
@sigmavirus24 That makes perfect sense, thanks for the explanation.

**Comment by sigmavirus24** [comment]
You're welcome @tmenier :)
