### ISSUE TITLE
fake_value cookie removed, which breaks a test in requests

### ISSUE THREAD

**Issue by kevin1024** [kennethreitz/httpbin#380]
This commit: 791e31cba4a4545352fa7d6e2d7019910166160a  removed the cookie that was always set on the digest endpoint, which breaks a test in requests (see also: [this travis failure]( https://travis-ci.org/requests/requests/jobs/268971293))

There was some old (never-resolved) discussion of this odd feature here: kennethreitz/httpbin#124

Paging @sigmavirus24 - should we add this behavior back?

See also: requests/requests#4263

**Comment by sigmavirus24** [comment]
Perhaps it'd be better to do that in a different way. Not ever HTTP client wants to handle Cookies as part of HTTP Digest even though that's patently wrong.

Requests has a test dependent upon that because we broke that at one point and were relying on being able to use HTTPbin to provide us the behaviour so we could verify it.

**Comment by kennethreitz** [comment]
Pull requests break everything around me.
