### ISSUE TITLE
Add support for IPv6

### ISSUE THREAD

**Issue by juanfra684** [kennethreitz/httpbin#57]
Can you add support for IPv6 to httpbin.org?

$ wget -6 http://httpbin.org/ip
--2012-07-24 02:04:19--  http://httpbin.org/ip
Resolving httpbin.org... failed: Name or service not known.
wget: unable to resolve host address “httpbin.org”

**Comment by gruns** [comment]
+1

Please add IPv6 support.

**Comment by toreanderson** [comment]
Was this issue closed by mistake, or was it fixed when closed but later regressed?

At the time of writing, it does not seem to work:

```console
$ host -t AAAA httpbin.org
httpbin.org has no AAAA record
$ curl https://httpbin.org/ip
{
  "origin": "84.214.x.y"
}
````

These tests were done from a dual-stacked machine, so `curl` would have preferred to use IPv6 if it could have, as demonstrated by using a different _print my ip_-service that is IPv6 capable:

```console
$ curl http://icanhazip.com
2a02:fe0:x:y:825e:b586:2ada:4d2e
$ curl -4 http://icanhazip.com
84.214.x.y
````

**Comment by sigmavirus24** [comment]
I don't know why @kennethreitz closed this but I'll reiterate that this isn't a bug in the application code. We and `icanhazip` work the same way, we both use `remote_addr` from the `request` object in Flask. The difference is that `httpbin` is deployed on Heroku so we also return `X-Forwarded-For`. Heroku [does not have IPv6](https://kb.heroku.com/apple-has-rejected-my-application-because-heroku-does-not-support-ipv6) support thus this is purely a deployment issue.

**Comment by ikomwrestling** [comment]
Few years have passed and httpbin still have no IPv6 support.

@kennethreitz Please add support for IPv6.

**Comment by ad-m** [comment]
Heroku does not support IPv6 ( https://help.heroku.com/I8L6RW01/does-heroku-support-ipv6 ). Therefore, the change requires a complete change in the way the application is deployed.

**Comment by ssbarnea** [comment]
Any chance to make this happen? lacking support for ipv6 is critical for http verification. Broken ipv6 is a very common error.

**Comment by wanis-fahmy** [comment]
I just used https://mockbin.org/ which has support for IPv6
